#!/bin/sh

set -euo pipefail

tmp="/tmp/$(basename $0)-$$"
function="${LAMBDA_TASK_ROOT}/${_HANDLER}"

while true; do
  HEADERS="$(mktemp)"
  curl -sS -LD "$HEADERS" -X GET "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next" > ${tmp}-event
  REQUEST_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)

  ${function} ${tmp}-event > ${tmp}-response

  curl -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$REQUEST_ID/response" -d "$(cat ${tmp}-response)"
done